# Centralized configuration for all tools
FUTURES_FORWARDS_TOOL_CONFIG = {
    "forward_pricing_no_income": {
        "title": "Forward Pricing: No Income",
        "description": "Calculate the forward price for an investment asset with no income.",
        "url": "/tools/futures-forwards/forward-pricing/forward_pricing_no_income",
        "inputs": [
            {
                "label": "Asset Price (S₀)",
                "id": "spot_price",
                "type": "number",
                "placeholder": "100",
                "step": "any",
            },
            {
                "label": "Risk-Free Rate (r)",
                "id": "risk_free_rate",
                "type": "number",
                "placeholder": "0.05",
                "step": "any",
            },
            {
                "label": "Time to Maturity (T)",
                "id": "time_to_maturity",
                "type": "number",
                "placeholder": "1 (year)",
                "step": "any",
            },
        ],
        "outputs": ["Forward Price (F₀)"],
        "visualization": False,
        "keywords": [
            "forward pricing",
            "no income",
            "investment asset",
            "risk-free rate",
            "forward contracts",
            "financial derivatives",
            "time to maturity",
            "pricing model",
            "cost of carry",
            "simple forward",
        ],
    },
    "forward_pricing_with_income": {
        "title": "Forward Pricing: With Income",
        "description": "Calculate the forward price for an investment asset with known income.",
        "url": "/tools/futures-forwards/forward-pricing/forward_pricing_with_income",
        "inputs": [
            {
                "label": "Asset Price (S₀)",
                "id": "spot_price",
                "type": "number",
                "placeholder": "100",
                "step": "any",
            },
            {
                "label": "Income (I)",
                "id": "income",
                "type": "number",
                "placeholder": "5",
                "step": "any",
            },
            {
                "label": "Risk-Free Rate (r)",
                "id": "risk_free_rate",
                "type": "number",
                "placeholder": "0.05",
                "step": "any",
            },
            {
                "label": "Time to Maturity (T)",
                "id": "time_to_maturity",
                "type": "number",
                "placeholder": "1",
                "step": "any",
            },
        ],
        "outputs": ["Forward Price (F₀)"],
        "visualization": False,
        "keywords": [
            "forward pricing",
            "income asset",
            "investment income",
            "financial asset",
            "asset valuation",
            "pricing formula",
            "derivatives pricing",
            "time to maturity",
            "forward contract income",
            "pricing income assets",
        ],
    },
    "forward_pricing_with_yield": {
        "title": "Forward Pricing: With Yield",
        "description": "Calculate the forward price for an investment asset with known yield.",
        "url": "/tools/futures-forwards/forward-pricing/forward_pricing_with_yield",
        "inputs": [
            {
                "label": "Asset Price (S₀)",
                "id": "spot_price",
                "type": "number",
                "placeholder": "100",
                "step": "any",
            },
            {
                "label": "Yield Rate (q)",
                "id": "yield_rate",
                "type": "number",
                "placeholder": "0.02",
                "step": "any",
            },
            {
                "label": "Risk-Free Rate (r)",
                "id": "risk_free_rate",
                "type": "number",
                "placeholder": "0.05",
                "step": "any",
            },
            {
                "label": "Time to Maturity (T)",
                "id": "time_to_maturity",
                "type": "number",
                "placeholder": "1",
                "step": "any",
            },
        ],
        "outputs": ["Forward Price (F₀)"],
        "visualization": False,
        "keywords": [
            "forward pricing",
            "yield rate",
            "asset yield",
            "investment yield",
            "pricing model",
            "financial derivatives",
            "forward contracts",
            "risk-free rate",
            "yield calculation",
            "time to maturity",
        ],
    },
    "forward_pricing_foreign_currency": {
        "title": "Forward Pricing: Foreign Currency",
        "description": "Calculate the forward price of a foreign currency using interest rate parity.",
        "url": "/tools/futures-forwards/forward-pricing/forward_pricing_foreign_currency",
        "inputs": [
            {
                "label": "Spot Price (S₀)",
                "id": "spot_price",
                "type": "number",
                "placeholder": "1.25",
                "step": "any",
            },
            {
                "label": "Domestic Risk-Free Rate (rₒ)",
                "id": "domestic_rate",
                "type": "number",
                "placeholder": "0.05",
                "step": "any",
            },
            {
                "label": "Foreign Risk-Free Rate (rₓ)",
                "id": "foreign_rate",
                "type": "number",
                "placeholder": "0.03",
                "step": "any",
            },
            {
                "label": "Time to Maturity (T)",
                "id": "time_to_maturity",
                "type": "number",
                "placeholder": "1",
                "step": "any",
            },
        ],
        "outputs": ["Forward Price (F₀)"],
        "visualization": False,
        "keywords": [
            "forward pricing",
            "foreign currency",
            "interest rate parity",
            "forex pricing",
            "currency hedging",
            "spot price",
            "domestic risk-free rate",
            "foreign risk-free rate",
            "forward contracts",
            "fx forward",
        ],
    },
    "futures_pricing_stock_index": {
        "title": "Futures Pricing: Stock Index with Dividend Yield",
        "description": "Calculate the futures price of a stock index considering dividend yield.",
        "url": "/tools/futures-forwards/futures-pricing/futures_pricing_stock_index",
        "inputs": [
            {
                "label": "Spot Price (S₀)",
                "id": "spot_price",
                "type": "number",
                "placeholder": "100",
                "step": "any",
            },
            {
                "label": "Dividend Yield (q)",
                "id": "dividend_yield",
                "type": "number",
                "placeholder": "0.02",
                "step": "any",
            },
            {
                "label": "Risk-Free Rate (r)",
                "id": "risk_free_rate",
                "type": "number",
                "placeholder": "0.05",
                "step": "any",
            },
            {
                "label": "Time to Maturity (T)",
                "id": "time_to_maturity",
                "type": "number",
                "placeholder": "1",
                "step": "any",
            },
        ],
        "outputs": ["Futures Price (F₀)"],
        "visualization": False,
        "keywords": [
            "futures pricing",
            "stock index",
            "dividend yield",
            "index pricing",
            "risk-free rate",
            "financial derivatives",
            "pricing models",
            "investment valuation",
            "time to maturity",
            "index futures",
        ],
    },
    "futures_pricing_with_storage": {
        "title": "Futures Pricing: Commodity with Storage Costs",
        "description": "Calculate the futures price of a commodity with fixed storage costs.",
        "url": "/tools/futures-forwards/futures-pricing/futures_pricing_with_storage",
        "inputs": [
            {
                "label": "Spot Price (S₀)",
                "id": "spot_price",
                "type": "number",
                "placeholder": "100",
                "step": "any",
            },
            {
                "label": "Storage Costs (U)",
                "id": "storage_costs",
                "type": "number",
                "placeholder": "5",
                "step": "any",
            },
            {
                "label": "Risk-Free Rate (r)",
                "id": "risk_free_rate",
                "type": "number",
                "placeholder": "0.05",
                "step": "any",
            },
            {
                "label": "Time to Maturity (T)",
                "id": "time_to_maturity",
                "type": "number",
                "placeholder": "1",
                "step": "any",
            },
        ],
        "outputs": ["Futures Price (F₀)"],
        "visualization": False,
        "keywords": [
            "futures pricing",
            "commodity futures",
            "storage costs",
            "risk-free rate",
            "financial derivatives",
            "commodity valuation",
            "pricing models",
            "time to maturity",
            "cost of carry",
            "commodity contracts",
        ],
    },
    "futures_pricing_proportional_costs_yield": {
        "title": "Futures Pricing: Commodity with Proportional Storage Costs and Convenience Yield",
        "description": "Calculate the futures price of a commodity with proportional storage costs and convenience yield.",
        "url": "/tools/futures-forwards/futures-pricing/futures_pricing_proportional_costs_yield",
        "inputs": [
            {
                "label": "Spot Price (S₀)",
                "id": "spot_price",
                "type": "number",
                "placeholder": "100",
                "step": "any",
            },
            {
                "label": "Proportional Storage Cost (u)",
                "id": "storage_cost_proportional",
                "type": "number",
                "placeholder": "0.01",
                "step": "any",
            },
            {
                "label": "Risk-Free Rate (r)",
                "id": "risk_free_rate",
                "type": "number",
                "placeholder": "0.05",
                "step": "any",
            },
            {
                "label": "Convenience Yield (y)",
                "id": "convenience_yield",
                "type": "number",
                "placeholder": "0.02",
                "step": "any",
            },
            {
                "label": "Time to Maturity (T)",
                "id": "time_to_maturity",
                "type": "number",
                "placeholder": "1",
                "step": "any",
            },
        ],
        "outputs": ["Futures Price (F₀)"],
        "visualization": False,
        "keywords": [
            "futures pricing",
            "proportional storage costs",
            "convenience yield",
            "commodity futures",
            "risk-free rate",
            "financial derivatives",
            "pricing models",
            "commodity valuation",
            "time to maturity",
            "storage cost pricing",
        ],
    },
    "futures_pricing_nonproportional_costs_yield": {
        "title": "Futures Pricing: Commodity with Non-Proportional Storage Costs and Convenience Yield",
        "description": "Calculate the futures price of a commodity with fixed storage costs and convenience yield.",
        "url": "/tools/futures-forwards/futures-pricing/futures_pricing_nonproportional_costs_yield",
        "inputs": [
            {
                "label": "Spot Price (S₀)",
                "id": "spot_price",
                "type": "number",
                "placeholder": "100",
                "step": "any",
            },
            {
                "label": "Storage Costs (U)",
                "id": "storage_costs",
                "type": "number",
                "placeholder": "5",
                "step": "any",
            },
            {
                "label": "Risk-Free Rate (r)",
                "id": "risk_free_rate",
                "type": "number",
                "placeholder": "0.05",
                "step": "any",
            },
            {
                "label": "Convenience Yield (y)",
                "id": "convenience_yield",
                "type": "number",
                "placeholder": "0.02",
                "step": "any",
            },
            {
                "label": "Time to Maturity (T)",
                "id": "time_to_maturity",
                "type": "number",
                "placeholder": "1",
                "step": "any",
            },
        ],
        "outputs": ["Futures Price (F₀)"],
        "visualization": False,
        "keywords": [
            "futures pricing",
            "non-proportional storage costs",
            "convenience yield",
            "commodity pricing",
            "financial derivatives",
            "pricing models",
            "storage costs",
            "risk-free rate",
            "time to maturity",
            "commodity contracts",
        ],
    },
    "futures_pricing_cost_of_carry": {
        "title": "Futures Pricing: Investment Asset (Cost of Carry)",
        "description": "Calculate the futures price of an investment asset using cost of carry.",
        "url": "/tools/futures-forwards/futures-pricing/futures_pricing_cost_of_carry",
        "inputs": [
            {
                "label": "Spot Price (S₀)",
                "id": "spot_price",
                "type": "number",
                "placeholder": "100",
                "step": "any",
            },
            {
                "label": "Cost of Carry (c)",
                "id": "cost_of_carry",
                "type": "number",
                "placeholder": "0.03",
                "step": "any",
            },
            {
                "label": "Time to Maturity (T)",
                "id": "time_to_maturity",
                "type": "number",
                "placeholder": "1",
                "step": "any",
            },
        ],
        "outputs": ["Futures Price (F₀)"],
        "visualization": False,
        "keywords": [
            "futures pricing",
            "investment asset",
            "cost of carry",
            "pricing model",
            "risk-free rate",
            "financial derivatives",
            "asset valuation",
            "time to maturity",
            "pricing futures",
            "investment contracts",
        ],
    },
    "futures_pricing_cost_of_carry_yield": {
        "title": "Futures Pricing: Consumption Asset (Cost of Carry with Convenience Yield)",
        "description": "Calculate the futures price of a consumption asset using cost of carry and convenience yield.",
        "url": "/tools/futures-forwards/futures-pricing/futures_pricing_cost_of_carry_yield",
        "inputs": [
            {
                "label": "Spot Price (S₀)",
                "id": "spot_price",
                "type": "number",
                "placeholder": "100",
                "step": "any",
            },
            {
                "label": "Cost of Carry (c)",
                "id": "cost_of_carry",
                "type": "number",
                "placeholder": "0.03",
                "step": "any",
            },
            {
                "label": "Convenience Yield (y)",
                "id": "convenience_yield",
                "type": "number",
                "placeholder": "0.02",
                "step": "any",
            },
            {
                "label": "Time to Maturity (T)",
                "id": "time_to_maturity",
                "type": "number",
                "placeholder": "1",
                "step": "any",
            },
        ],
        "outputs": ["Futures Price (F₀)"],
        "visualization": False,
        "keywords": [
            "futures pricing",
            "consumption asset",
            "cost of carry",
            "convenience yield",
            "commodity futures",
            "financial derivatives",
            "pricing models",
            "asset valuation",
            "time to maturity",
            "pricing consumption assets",
        ],
    },
}
